import { useCallback, useEffect, useMemo, useState } from 'react'
import usePrayerTimes from '../hooks/usePrayerTimes'
import {
  addDays,
  format12h,
  formatCountdown,
  isSameDay,
  parseApiTimeToDate,
} from '../utils/time'
import './PrayerTimes.css'

type PrayerRow = {
  key: 'Fajr' | 'Sunrise' | 'Dhuhr' | 'Asr' | 'Maghrib' | 'Isha'
  label: string
}

const PRAYERS: PrayerRow[] = [
  { key: 'Fajr', label: 'Fajr' },
  { key: 'Sunrise', label: 'Sunrise' },
  { key: 'Dhuhr', label: 'Dhuhr' },
  { key: 'Asr', label: 'Asr' },
  { key: 'Maghrib', label: 'Maghrib' },
  { key: 'Isha', label: 'Isha' },
]

const PrayerTimes = () => {
  const [selectedDate, setSelectedDate] = useState(() => {
    const d = new Date()
    d.setHours(0, 0, 0, 0)
    return d
  })

  const { prayerTimes, meta, loading } = usePrayerTimes('Schenectady', 'US', selectedDate, true)
  const isToday = isSameDay(selectedDate, new Date())
  const tomorrowDate = useMemo(() => addDays(selectedDate, 1), [selectedDate])
  const { prayerTimes: tomorrowPrayerTimes } = usePrayerTimes('Schenectady', 'US', tomorrowDate, isToday)

  const schedule = useMemo(() => {
    if (!prayerTimes) return []
    return PRAYERS.map((p) => ({
      ...p,
      timeRaw: prayerTimes[p.key] || '',
      time12: prayerTimes[p.key] ? format12h(prayerTimes[p.key] as string) : '—',
      dateTime: prayerTimes[p.key] ? parseApiTimeToDate(selectedDate, prayerTimes[p.key] as string) : null,
    }))
  }, [prayerTimes, selectedDate])

  const [nowTick, setNowTick] = useState(() => Date.now())
  useEffect(() => {
    if (!isToday) return
    const id = window.setInterval(() => setNowTick(Date.now()), 1000)
    return () => window.clearInterval(id)
  }, [isToday])

  const nextInfo = useMemo(() => {
    if (!isToday || schedule.length === 0) return null
    const now = new Date(nowTick)

    const upcoming = schedule.find((p) => p.dateTime && p.dateTime.getTime() > now.getTime())
    if (upcoming?.dateTime) {
      const diffSec = (upcoming.dateTime.getTime() - now.getTime()) / 1000
      return { nextKey: upcoming.key, nextLabel: upcoming.label, seconds: diffSec }
    }

    // After Isha: count down to tomorrow's Fajr if we have it
    const tf = tomorrowPrayerTimes?.Fajr
    if (tf) {
      const fajrTomorrow = parseApiTimeToDate(tomorrowDate, tf)
      const diffSec = (fajrTomorrow.getTime() - now.getTime()) / 1000
      return { nextKey: 'Fajr' as const, nextLabel: 'Fajr', seconds: diffSec }
    }

    return { nextKey: 'Fajr' as const, nextLabel: 'Fajr', seconds: 0 }
  }, [isToday, nowTick, schedule, tomorrowPrayerTimes, tomorrowDate])

  const currentKey = useMemo(() => {
    if (!isToday || schedule.length === 0) return null
    const now = new Date(nowTick)
    const lastPassed = [...schedule].reverse().find((p) => p.dateTime && p.dateTime.getTime() <= now.getTime())
    if (lastPassed) return lastPassed.key
    // Before Fajr: highlight Isha (previous prayer)
    return 'Isha'
  }, [isToday, nowTick, schedule])

  const activeKey = currentKey
  const countdownText = nextInfo ? formatCountdown(nextInfo.seconds) : '—'

  const dateTitle = meta.readableDate || selectedDate.toLocaleDateString(undefined, { day: '2-digit', month: 'long', year: 'numeric' })
  const hijriTitle = meta.hijriDate ? meta.hijriDate : ''

  const handleDownload = useCallback(() => {
    const lines: string[] = []
    lines.push(`Prayer Times - ${dateTitle}`)
    if (hijriTitle) lines.push(`Hijri: ${hijriTitle}`)
    lines.push('')
    for (const p of schedule) {
      lines.push(`${p.label}: ${p.time12}`)
    }
    lines.push('')
    lines.push('Jummah: 1:00 PM')
    lines.push('')
    lines.push('Generated by ICCD website')

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `prayer-times-${dateTitle.replace(/\s+/g, '-').toLowerCase()}.txt`
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }, [dateTitle, hijriTitle, schedule])

  return (
    <section id="prayer-times" className="prayer-times section-bg">
      <div className="container">
        <div className="section-head">
          <h2 className="section-title" style={{paddingBottom: "10px"}}>Prayer Times</h2>
        </div>

        <div className="prayer-panel">
          <div className="pt-top">
            <div className="pt-meta">
              <div className="pt-title-row">
                <div className="pt-title">Time until next prayer</div>
                {isToday && nextInfo ? (
                  <div className="pt-countdown" aria-label="Countdown to next prayer">
                    {countdownText}
                  </div>
                ) : null}
              </div>
              {!isToday ? (
                <div className="pt-subtitle">Select a date to view the schedule</div>
              ) : null}
            </div>
          </div>

          <div className="pt-datebar">
            <button
              className="pt-arrow"
              onClick={() => setSelectedDate((d) => addDays(d, -1))}
              aria-label="Previous day"
            >
              ‹
            </button>

            <div className="pt-date">
              <div className="pt-date-main">{dateTitle}</div>
              {hijriTitle ? <div className="pt-date-sub">{hijriTitle}</div> : null}
            </div>

            <button
              className="pt-arrow"
              onClick={() => setSelectedDate((d) => addDays(d, 1))}
              aria-label="Next day"
            >
              ›
            </button>
          </div>

          {loading ? (
            <div className="pt-loading">
              <div className="loading-spinner" />
              <div>Loading prayer times…</div>
            </div>
          ) : (
            <div className="pt-list" role="list">
              {schedule.map((p) => (
                <div
                  key={p.key}
                  className={`pt-row ${activeKey === p.key ? 'pt-row--active' : ''}`}
                  role="listitem"
                >
                  <div className="pt-row-left">
                    <div className="pt-row-label">{p.label}</div>
                  </div>

                  <div className="pt-row-right">
                    <div className="pt-row-time">{p.time12}</div>
                  </div>
                </div>
              ))}
            </div>
          )}

          <div className="pt-jummah-bottom" aria-label="Jummah time">
            Jummah:  1:00 PM
          </div>

          <button className="pt-download pt-download--bottom" type="button" onClick={handleDownload}>
            Download Prayer Sheet
          </button>

          <div className="pt-api-note">
            Powered by Aladhan Prayer Times API ({' '}
            <a href="https://aladhan.com/prayer-times-api" target="_blank" rel="noreferrer">
              docs
            </a>
            )
          </div>
        </div>
      </div>
    </section>
  )
}

export default PrayerTimes